apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: development
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: development
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
~                      