apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
    ver: "1.0"
    release: stable
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
    ver: "1.0"
