apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: development
  labels:
    app: guestbook
    tier: frontend
    ver: "1.0"
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  #type: NodePort 
  #type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
    ver: "1.0"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: development
  labels:
    app: redis
    role: master
    tier: backend
    ver: "1.0"
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
    ver: "1.0"
---

apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: development
  labels:
    app: redis
    role: slave
    tier: backend
    ver: "1.0"
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
    ver: "1.0"
